// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHqZjUBV-n6vnpbUHHhCRepdxS-J3TbPA',
    appId: '1:327310385242:web:4f1cb7c59422f95e017863',
    messagingSenderId: '327310385242',
    projectId: 'chatapp-d5506',
    authDomain: 'chatapp-d5506.firebaseapp.com',
    storageBucket: 'chatapp-d5506.appspot.com',
    measurementId: 'G-80NLBJ6TZ9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD2jYivrg51im7EsRDnjbOptO4kcrdn5oM',
    appId: '1:327310385242:android:e1eac179a16de6c0017863',
    messagingSenderId: '327310385242',
    projectId: 'chatapp-d5506',
    storageBucket: 'chatapp-d5506.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAu7bnSiKhPW1nbiVFD7Y9B5gCHhzifuHw',
    appId: '1:327310385242:ios:56976c1444f17203017863',
    messagingSenderId: '327310385242',
    projectId: 'chatapp-d5506',
    storageBucket: 'chatapp-d5506.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAu7bnSiKhPW1nbiVFD7Y9B5gCHhzifuHw',
    appId: '1:327310385242:ios:56976c1444f17203017863',
    messagingSenderId: '327310385242',
    projectId: 'chatapp-d5506',
    storageBucket: 'chatapp-d5506.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHqZjUBV-n6vnpbUHHhCRepdxS-J3TbPA',
    appId: '1:327310385242:web:a9e55ca9bf3cc83c017863',
    messagingSenderId: '327310385242',
    projectId: 'chatapp-d5506',
    authDomain: 'chatapp-d5506.firebaseapp.com',
    storageBucket: 'chatapp-d5506.appspot.com',
    measurementId: 'G-Y1WF6VF4RV',
  );
}
